// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: assets/v1/assets.proto

package assetsv1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "go.datalift.io/datalift/api/assets/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// AssetsAPIName is the fully-qualified name of the AssetsAPI service.
	AssetsAPIName = "datalift.assets.v1.AssetsAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AssetsAPIFetchProcedure is the fully-qualified name of the AssetsAPI's Fetch RPC.
	AssetsAPIFetchProcedure = "/datalift.assets.v1.AssetsAPI/Fetch"
)

// AssetsAPIClient is a client for the datalift.assets.v1.AssetsAPI service.
type AssetsAPIClient interface {
	// Fetch is a simple endpoint that is used to execute middleware (e.g. authentication) before serving an asset.
	Fetch(context.Context, *connect_go.Request[v1.FetchRequest]) (*connect_go.Response[v1.FetchResponse], error)
}

// NewAssetsAPIClient constructs a client for the datalift.assets.v1.AssetsAPI service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAssetsAPIClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) AssetsAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &assetsAPIClient{
		fetch: connect_go.NewClient[v1.FetchRequest, v1.FetchResponse](
			httpClient,
			baseURL+AssetsAPIFetchProcedure,
			opts...,
		),
	}
}

// assetsAPIClient implements AssetsAPIClient.
type assetsAPIClient struct {
	fetch *connect_go.Client[v1.FetchRequest, v1.FetchResponse]
}

// Fetch calls datalift.assets.v1.AssetsAPI.Fetch.
func (c *assetsAPIClient) Fetch(ctx context.Context, req *connect_go.Request[v1.FetchRequest]) (*connect_go.Response[v1.FetchResponse], error) {
	return c.fetch.CallUnary(ctx, req)
}

// AssetsAPIHandler is an implementation of the datalift.assets.v1.AssetsAPI service.
type AssetsAPIHandler interface {
	// Fetch is a simple endpoint that is used to execute middleware (e.g. authentication) before serving an asset.
	Fetch(context.Context, *connect_go.Request[v1.FetchRequest]) (*connect_go.Response[v1.FetchResponse], error)
}

// NewAssetsAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAssetsAPIHandler(svc AssetsAPIHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	assetsAPIFetchHandler := connect_go.NewUnaryHandler(
		AssetsAPIFetchProcedure,
		svc.Fetch,
		opts...,
	)
	return "/datalift.assets.v1.AssetsAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AssetsAPIFetchProcedure:
			assetsAPIFetchHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAssetsAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedAssetsAPIHandler struct{}

func (UnimplementedAssetsAPIHandler) Fetch(context.Context, *connect_go.Request[v1.FetchRequest]) (*connect_go.Response[v1.FetchResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("datalift.assets.v1.AssetsAPI.Fetch is not implemented"))
}
