version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datalift
      POSTGRES_USER: datalift
      POSTGRES_PASSWORD: datalift
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    network_mode: "bridge"
