gateway:
  logger:
    pretty: true
    level: DEBUG
  accesslog:
    # log http 5xx errors by default
    status_code_filters:
      # Unknown - http.StatusInternalServerError
      - equals: 2
      # DeadlineExceeded - http.StatusInternalServerError
      - equals: 4
      # Unimplemented - http.StatusNotImplemented
      - equals: 12
      # Unavailable - http.StatusServiceUnavailable
      - equals: 14
  stats:
    flush_interval: 1s
    log_reporter: {}
  timeouts:
    default: 15s
  middleware:
    - name: datalift.middleware.stats
    - name: datalift.middleware.validate
    - name: datalift.middleware.authn
  listener:
    tcp:
      address: 0.0.0.0
      port: 8080
      secure: false
modules:
  - name: datalift.module.assets
  - name: datalift.module.healthcheck
  - name: datalift.module.authn
  - name: datalift.module.application
services:
  - name: datalift.service.db.postgres
    typed_config:
      "@type": types.google.com/datalift.config.service.db.postgres.v1.Config
      connection:
        host: 0.0.0.0
        port: 5432
        user: datalift
        ssl_mode: DISABLE
        dbname: datalift
        password: datalift
  - name: datalift.service.authn
    typed_config:
      "@type": types.google.com/datalift.config.service.authn.v1.Config
      oidc:
        issuer: https://accounts.google.com
        client_id: 999252236553-2dd37nnqcf5ta2bh1lv12re5h5nd1jp3.apps.googleusercontent.com
        client_secret: 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
        redirect_url: "http://localhost:8080/auth/callback"
        subject_claim_name_override: name
        scopes:
          - openid
          - profile
          - email
      session_secret: 823916d0-cb6d-4aa5-858c-9630ae6a5634
      enable_service_token_creation: true
  - name: datalift.service.application
  - name: datalift.service.workflow