gateway:
  logger:
    pretty: true
    level: DEBUG
  accesslog:
    # log http 5xx errors by default
    status_code_filters:
      # Unknown - http.StatusInternalServerError
      - equals: 2
      # DeadlineExceeded - http.StatusInternalServerError
      - equals: 4
      # Unimplemented - http.StatusNotImplemented
      - equals: 12
      # Unavailable - http.StatusServiceUnavailable
      - equals: 14
  stats:
    flush_interval: 1s
    log_reporter: {}
  timeouts:
    default: 15s
  middleware:
    - name: datalift.middleware.stats
    - name: datalift.middleware.validate
    - name: datalift.middleware.authn
  listener:
    tcp:
      address: 0.0.0.0
      port: 8080
      secure: false
modules:
  - name: datalift.module.assets
  - name: datalift.module.healthcheck
  - name: datalift.module.authn
  - name: datalift.module.application
