// @generated by protoc-gen-connect-es v0.10.1
// @generated from file audit/v1/audit.proto (package datalift.audit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetEventRequest, GetEventResponse, GetEventsRequest, GetEventsResponse } from "./audit_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.audit.v1.AuditAPI
 */
export declare const AuditAPI: {
  readonly typeName: "datalift.audit.v1.AuditAPI",
  readonly methods: {
    /**
     * @generated from rpc datalift.audit.v1.AuditAPI.GetEvents
     */
    readonly getEvents: {
      readonly name: "GetEvents",
      readonly I: typeof GetEventsRequest,
      readonly O: typeof GetEventsResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.audit.v1.AuditAPI.GetEvent
     */
    readonly getEvent: {
      readonly name: "GetEvent",
      readonly I: typeof GetEventRequest,
      readonly O: typeof GetEventResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

