// @generated by protoc-gen-connect-es v0.10.1
// @generated from file healthcheck/v1/healthcheck.proto (package datalift.healthcheck.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthcheckRequest, HealthcheckResponse } from "./healthcheck_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.healthcheck.v1.HealthcheckAPI
 */
export declare const HealthcheckAPI: {
  readonly typeName: "datalift.healthcheck.v1.HealthcheckAPI",
  readonly methods: {
    /**
     * @generated from rpc datalift.healthcheck.v1.HealthcheckAPI.Healthcheck
     */
    readonly healthcheck: {
      readonly name: "Healthcheck",
      readonly I: typeof HealthcheckRequest,
      readonly O: typeof HealthcheckResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

