// @generated by protoc-gen-connect-es v0.10.1
// @generated from file assets/v1/assets.proto (package datalift.assets.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { FetchRequest, FetchResponse } from "./assets_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.assets.v1.AssetsAPI
 */
export declare const AssetsAPI: {
  readonly typeName: "datalift.assets.v1.AssetsAPI",
  readonly methods: {
    /**
     * Fetch is a simple endpoint that is used to execute middleware (e.g. authentication) before serving an asset.
     *
     * @generated from rpc datalift.assets.v1.AssetsAPI.Fetch
     */
    readonly fetch: {
      readonly name: "Fetch",
      readonly I: typeof FetchRequest,
      readonly O: typeof FetchResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

