// @generated by protoc-gen-connect-es v0.10.1
// @generated from file audit/v1/audit.proto (package datalift.audit.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetEventRequest, GetEventResponse, GetEventsRequest, GetEventsResponse } from "./audit_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.audit.v1.AuditAPI
 */
export const AuditAPI = {
  typeName: "datalift.audit.v1.AuditAPI",
  methods: {
    /**
     * @generated from rpc datalift.audit.v1.AuditAPI.GetEvents
     */
    getEvents: {
      name: "GetEvents",
      I: GetEventsRequest,
      O: GetEventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.audit.v1.AuditAPI.GetEvent
     */
    getEvent: {
      name: "GetEvent",
      I: GetEventRequest,
      O: GetEventResponse,
      kind: MethodKind.Unary,
    },
  }
};

