// @generated by protoc-gen-connect-es v0.10.1
// @generated from file application/v1/application.proto (package datalift.application.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateApplicationRequest, CreateApplicationResponse, DeleteApplicationRequest, DeleteApplicationResponse, GetApplicationRequest, GetApplicationResponse, ListApplicationsRequest, ListApplicationsResponse, UpdateApplicationRequest, UpdateApplicationResponse } from "./application_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.application.v1.ApplicationAPI
 */
export const ApplicationAPI = {
  typeName: "datalift.application.v1.ApplicationAPI",
  methods: {
    /**
     * @generated from rpc datalift.application.v1.ApplicationAPI.CreateApplication
     */
    createApplication: {
      name: "CreateApplication",
      I: CreateApplicationRequest,
      O: CreateApplicationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.application.v1.ApplicationAPI.DeleteApplication
     */
    deleteApplication: {
      name: "DeleteApplication",
      I: DeleteApplicationRequest,
      O: DeleteApplicationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.application.v1.ApplicationAPI.GetApplication
     */
    getApplication: {
      name: "GetApplication",
      I: GetApplicationRequest,
      O: GetApplicationResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.application.v1.ApplicationAPI.ListApplications
     */
    listApplications: {
      name: "ListApplications",
      I: ListApplicationsRequest,
      O: ListApplicationsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.application.v1.ApplicationAPI.UpdateApplication
     */
    updateApplication: {
      name: "UpdateApplication",
      I: UpdateApplicationRequest,
      O: UpdateApplicationResponse,
      kind: MethodKind.Unary,
    },
  }
};

