// @generated by protoc-gen-es v1.2.1
// @generated from file application/v1/application.proto (package datalift.application.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from message datalift.application.v1.Application
 */
export const Application = proto3.makeMessageType(
  "datalift.application.v1.Application",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "created_at", kind: "message", T: Timestamp },
    { no: 5, name: "created_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.application.v1.ApplicationQuery
 */
export const ApplicationQuery = proto3.makeMessageType(
  "datalift.application.v1.ApplicationQuery",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.application.v1.CreateApplicationRequest
 */
export const CreateApplicationRequest = proto3.makeMessageType(
  "datalift.application.v1.CreateApplicationRequest",
  () => [
    { no: 1, name: "application", kind: "message", T: Application },
  ],
);

/**
 * @generated from message datalift.application.v1.CreateApplicationResponse
 */
export const CreateApplicationResponse = proto3.makeMessageType(
  "datalift.application.v1.CreateApplicationResponse",
  [],
);

/**
 * @generated from message datalift.application.v1.DeleteApplicationRequest
 */
export const DeleteApplicationRequest = proto3.makeMessageType(
  "datalift.application.v1.DeleteApplicationRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.application.v1.DeleteApplicationResponse
 */
export const DeleteApplicationResponse = proto3.makeMessageType(
  "datalift.application.v1.DeleteApplicationResponse",
  [],
);

/**
 * @generated from message datalift.application.v1.GetApplicationRequest
 */
export const GetApplicationRequest = proto3.makeMessageType(
  "datalift.application.v1.GetApplicationRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.application.v1.GetApplicationResponse
 */
export const GetApplicationResponse = proto3.makeMessageType(
  "datalift.application.v1.GetApplicationResponse",
  () => [
    { no: 1, name: "application", kind: "message", T: Application },
  ],
);

/**
 * @generated from message datalift.application.v1.ListApplicationsRequest
 */
export const ListApplicationsRequest = proto3.makeMessageType(
  "datalift.application.v1.ListApplicationsRequest",
  [],
);

/**
 * @generated from message datalift.application.v1.ListApplicationsResponse
 */
export const ListApplicationsResponse = proto3.makeMessageType(
  "datalift.application.v1.ListApplicationsResponse",
  [],
);

/**
 * @generated from message datalift.application.v1.UpdateApplicationRequest
 */
export const UpdateApplicationRequest = proto3.makeMessageType(
  "datalift.application.v1.UpdateApplicationRequest",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.application.v1.UpdateApplicationResponse
 */
export const UpdateApplicationResponse = proto3.makeMessageType(
  "datalift.application.v1.UpdateApplicationResponse",
  [],
);

