// @generated by protoc-gen-es v1.2.1
// @generated from file application/v1/application.proto (package datalift.application.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message datalift.application.v1.Application
 */
export declare class Application extends Message<Application> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 4;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: string created_by = 5;
   */
  createdBy: string;

  constructor(data?: PartialMessage<Application>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.Application";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Application;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Application;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Application;

  static equals(a: Application | PlainMessage<Application> | undefined, b: Application | PlainMessage<Application> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.ApplicationQuery
 */
export declare class ApplicationQuery extends Message<ApplicationQuery> {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  constructor(data?: PartialMessage<ApplicationQuery>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.ApplicationQuery";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ApplicationQuery;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ApplicationQuery;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ApplicationQuery;

  static equals(a: ApplicationQuery | PlainMessage<ApplicationQuery> | undefined, b: ApplicationQuery | PlainMessage<ApplicationQuery> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.CreateApplicationRequest
 */
export declare class CreateApplicationRequest extends Message<CreateApplicationRequest> {
  /**
   * @generated from field: datalift.application.v1.Application application = 1;
   */
  application?: Application;

  constructor(data?: PartialMessage<CreateApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.CreateApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateApplicationRequest;

  static equals(a: CreateApplicationRequest | PlainMessage<CreateApplicationRequest> | undefined, b: CreateApplicationRequest | PlainMessage<CreateApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.CreateApplicationResponse
 */
export declare class CreateApplicationResponse extends Message<CreateApplicationResponse> {
  constructor(data?: PartialMessage<CreateApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.CreateApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CreateApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CreateApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CreateApplicationResponse;

  static equals(a: CreateApplicationResponse | PlainMessage<CreateApplicationResponse> | undefined, b: CreateApplicationResponse | PlainMessage<CreateApplicationResponse> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.DeleteApplicationRequest
 */
export declare class DeleteApplicationRequest extends Message<DeleteApplicationRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<DeleteApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.DeleteApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteApplicationRequest;

  static equals(a: DeleteApplicationRequest | PlainMessage<DeleteApplicationRequest> | undefined, b: DeleteApplicationRequest | PlainMessage<DeleteApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.DeleteApplicationResponse
 */
export declare class DeleteApplicationResponse extends Message<DeleteApplicationResponse> {
  constructor(data?: PartialMessage<DeleteApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.DeleteApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteApplicationResponse;

  static equals(a: DeleteApplicationResponse | PlainMessage<DeleteApplicationResponse> | undefined, b: DeleteApplicationResponse | PlainMessage<DeleteApplicationResponse> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.GetApplicationRequest
 */
export declare class GetApplicationRequest extends Message<GetApplicationRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<GetApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.GetApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetApplicationRequest;

  static equals(a: GetApplicationRequest | PlainMessage<GetApplicationRequest> | undefined, b: GetApplicationRequest | PlainMessage<GetApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.GetApplicationResponse
 */
export declare class GetApplicationResponse extends Message<GetApplicationResponse> {
  /**
   * @generated from field: datalift.application.v1.Application application = 1;
   */
  application?: Application;

  constructor(data?: PartialMessage<GetApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.GetApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetApplicationResponse;

  static equals(a: GetApplicationResponse | PlainMessage<GetApplicationResponse> | undefined, b: GetApplicationResponse | PlainMessage<GetApplicationResponse> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.ListApplicationsRequest
 */
export declare class ListApplicationsRequest extends Message<ListApplicationsRequest> {
  constructor(data?: PartialMessage<ListApplicationsRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.ListApplicationsRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListApplicationsRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListApplicationsRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListApplicationsRequest;

  static equals(a: ListApplicationsRequest | PlainMessage<ListApplicationsRequest> | undefined, b: ListApplicationsRequest | PlainMessage<ListApplicationsRequest> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.ListApplicationsResponse
 */
export declare class ListApplicationsResponse extends Message<ListApplicationsResponse> {
  constructor(data?: PartialMessage<ListApplicationsResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.ListApplicationsResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ListApplicationsResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ListApplicationsResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ListApplicationsResponse;

  static equals(a: ListApplicationsResponse | PlainMessage<ListApplicationsResponse> | undefined, b: ListApplicationsResponse | PlainMessage<ListApplicationsResponse> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.UpdateApplicationRequest
 */
export declare class UpdateApplicationRequest extends Message<UpdateApplicationRequest> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  constructor(data?: PartialMessage<UpdateApplicationRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.UpdateApplicationRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateApplicationRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateApplicationRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateApplicationRequest;

  static equals(a: UpdateApplicationRequest | PlainMessage<UpdateApplicationRequest> | undefined, b: UpdateApplicationRequest | PlainMessage<UpdateApplicationRequest> | undefined): boolean;
}

/**
 * @generated from message datalift.application.v1.UpdateApplicationResponse
 */
export declare class UpdateApplicationResponse extends Message<UpdateApplicationResponse> {
  constructor(data?: PartialMessage<UpdateApplicationResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "datalift.application.v1.UpdateApplicationResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UpdateApplicationResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UpdateApplicationResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UpdateApplicationResponse;

  static equals(a: UpdateApplicationResponse | PlainMessage<UpdateApplicationResponse> | undefined, b: UpdateApplicationResponse | PlainMessage<UpdateApplicationResponse> | undefined): boolean;
}

