// @generated by protoc-gen-es v1.2.1
// @generated from file common/v1/schema.proto (package datalift.common.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum datalift.common.v1.ActionType
 */
export const ActionType = proto3.makeEnum(
  "datalift.common.v1.ActionType",
  [
    {no: 0, name: "UNSPECIFIED"},
    {no: 1, name: "CREATE"},
    {no: 2, name: "READ"},
    {no: 3, name: "UPDATE"},
    {no: 4, name: "DELETE"},
  ],
);

/**
 * @generated from message datalift.common.v1.Action
 */
export const Action = proto3.makeMessageType(
  "datalift.common.v1.Action",
  () => [
    { no: 1, name: "type", kind: "enum", T: proto3.getEnumType(ActionType) },
  ],
);

/**
 * @generated from message datalift.common.v1.Pattern
 */
export const Pattern = proto3.makeMessageType(
  "datalift.common.v1.Pattern",
  () => [
    { no: 1, name: "type_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pattern", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.common.v1.Identifier
 */
export const Identifier = proto3.makeMessageType(
  "datalift.common.v1.Identifier",
  () => [
    { no: 1, name: "patterns", kind: "message", T: Pattern, repeated: true },
  ],
);

/**
 * @generated from message datalift.common.v1.Reference
 */
export const Reference = proto3.makeMessageType(
  "datalift.common.v1.Reference",
  () => [
    { no: 1, name: "fields", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * Message used to represent redacted messages.
 *
 * @generated from message datalift.common.v1.Redacted
 */
export const Redacted = proto3.makeMessageType(
  "datalift.common.v1.Redacted",
  () => [
    { no: 1, name: "redacted_type_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

