// @generated by protoc-gen-connect-es v0.10.1
// @generated from file authn/v1/authn.proto (package datalift.authn.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CallbackRequest, CallbackResponse, CreateTokenRequest, CreateTokenResponse, LoginRequest, LoginResponse } from "./authn_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.authn.v1.AuthnAPI
 */
export declare const AuthnAPI: {
  readonly typeName: "datalift.authn.v1.AuthnAPI",
  readonly methods: {
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.Login
     */
    readonly login: {
      readonly name: "Login",
      readonly I: typeof LoginRequest,
      readonly O: typeof LoginResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.Callback
     */
    readonly callback: {
      readonly name: "Callback",
      readonly I: typeof CallbackRequest,
      readonly O: typeof CallbackResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.CreateToken
     */
    readonly createToken: {
      readonly name: "CreateToken",
      readonly I: typeof CreateTokenRequest,
      readonly O: typeof CreateTokenResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

