// @generated by protoc-gen-es v1.2.1
// @generated from file authn/v1/authn.proto (package datalift.authn.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Duration, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message datalift.authn.v1.LoginRequest
 */
export const LoginRequest = proto3.makeMessageType(
  "datalift.authn.v1.LoginRequest",
  () => [
    { no: 1, name: "redirect_url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.authn.v1.LoginResponse
 */
export const LoginResponse = proto3.makeMessageType(
  "datalift.authn.v1.LoginResponse",
  () => [
    { no: 1, name: "auth_url", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "return" },
    { no: 2, name: "token", kind: "message", T: LoginResponse_Token, oneof: "return" },
  ],
);

/**
 * @generated from message datalift.authn.v1.LoginResponse.Token
 */
export const LoginResponse_Token = proto3.makeMessageType(
  "datalift.authn.v1.LoginResponse.Token",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
  {localName: "LoginResponse_Token"},
);

/**
 * See https://www.oauth.com/oauth2-servers/authorization/the-authorization-response/ for description of the parameters.
 *
 * @generated from message datalift.authn.v1.CallbackRequest
 */
export const CallbackRequest = proto3.makeMessageType(
  "datalift.authn.v1.CallbackRequest",
  () => [
    { no: 1, name: "code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "state", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "error", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "error_description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.authn.v1.CallbackResponse
 */
export const CallbackResponse = proto3.makeMessageType(
  "datalift.authn.v1.CallbackResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message datalift.authn.v1.CreateTokenRequest
 */
export const CreateTokenRequest = proto3.makeMessageType(
  "datalift.authn.v1.CreateTokenRequest",
  () => [
    { no: 1, name: "subject", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "expiry", kind: "message", T: Duration },
    { no: 3, name: "token_type", kind: "enum", T: proto3.getEnumType(CreateTokenRequest_TokenType) },
  ],
);

/**
 * @generated from enum datalift.authn.v1.CreateTokenRequest.TokenType
 */
export const CreateTokenRequest_TokenType = proto3.makeEnum(
  "datalift.authn.v1.CreateTokenRequest.TokenType",
  [
    {no: 0, name: "UNSPECIFIED"},
    {no: 1, name: "SERVICE"},
  ],
);

/**
 * @generated from message datalift.authn.v1.CreateTokenResponse
 */
export const CreateTokenResponse = proto3.makeMessageType(
  "datalift.authn.v1.CreateTokenResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

