// @generated by protoc-gen-connect-es v0.10.1
// @generated from file authn/v1/authn.proto (package datalift.authn.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CallbackRequest, CallbackResponse, CreateTokenRequest, CreateTokenResponse, LoginRequest, LoginResponse } from "./authn_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.authn.v1.AuthnAPI
 */
export const AuthnAPI = {
  typeName: "datalift.authn.v1.AuthnAPI",
  methods: {
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.Login
     */
    login: {
      name: "Login",
      I: LoginRequest,
      O: LoginResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.Callback
     */
    callback: {
      name: "Callback",
      I: CallbackRequest,
      O: CallbackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc datalift.authn.v1.AuthnAPI.CreateToken
     */
    createToken: {
      name: "CreateToken",
      I: CreateTokenRequest,
      O: CreateTokenResponse,
      kind: MethodKind.Unary,
    },
  }
};

