// @generated by protoc-gen-es v1.2.1
// @generated from file healthcheck/v1/healthcheck.proto (package datalift.healthcheck.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message datalift.healthcheck.v1.HealthcheckRequest
 */
export const HealthcheckRequest = proto3.makeMessageType(
  "datalift.healthcheck.v1.HealthcheckRequest",
  [],
);

/**
 * @generated from message datalift.healthcheck.v1.HealthcheckResponse
 */
export const HealthcheckResponse = proto3.makeMessageType(
  "datalift.healthcheck.v1.HealthcheckResponse",
  [],
);

