// @generated by protoc-gen-connect-es v0.10.1
// @generated from file healthcheck/v1/healthcheck.proto (package datalift.healthcheck.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthcheckRequest, HealthcheckResponse } from "./healthcheck_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service datalift.healthcheck.v1.HealthcheckAPI
 */
export const HealthcheckAPI = {
  typeName: "datalift.healthcheck.v1.HealthcheckAPI",
  methods: {
    /**
     * @generated from rpc datalift.healthcheck.v1.HealthcheckAPI.Healthcheck
     */
    healthcheck: {
      name: "Healthcheck",
      I: HealthcheckRequest,
      O: HealthcheckResponse,
      kind: MethodKind.Unary,
    },
  }
};

