name: scripts
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    paths:
    - '**.sh'
    - .github/workflows/shellcheck.yaml
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Shellcheck
      run: ./tools/shellcheck.sh